script:
- chmod +x run_test.sh
- chmod +x run_tests.sh
- ./run_tests.sh plus minus

# disabling email notifications
notifications:
  email: false
  webhooks: http://83.243.70.130:8080/rest/travis/hook